# Written by Cameron Haddock
# Submitted as a solution to Project Euler's Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#               1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fib_sum_even(max_value):
    cur = 1
    prev = 1
    sum_ = 0
    while True:
        new = cur + prev
        if new >= max_value:
            break
        prev = cur
        cur = new
        if(cur % 2 == 0):
            sum_ += cur
    return sum_
        
print(fib_sum_even(4000000))