# Written by Cameron Haddock
# Submitted as a solution to Project Euler's Problem 44

# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#           1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?


def gen_pen_nums(max_):
    pens = []
    for n in range(1,max_+1):
        pens.append(int(n*(3*n-1)/2))
    return pens

def pen_pairs(max_):
    P = gen_pen_nums(max_)
    pSet = set(P)
    for i in range(max_):
        for j in range(i,max_):
            if P[j] + P[i] > P[-1]:
                break
            if P[j] - P[i] in pSet and P[i] + P[j] in pSet:
                # print(i,j,P[i],P[j],P[i]+P[j],P[j]-P[i])
                return P[j] - P[i]

print(pen_pairs(10000))