# Written by Cameron Haddock
# Submitted as a solution to Project Euler's Problem 29

# How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?


def get_seq(max_a,max_b):
    seq = set()
    for a in range(2,max_a+1):
        for b in range(2,max_b+1):
            seq.add(a**b)
    return seq
            
print(len(get_seq(100,100)))